language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3
  - hhvm
before_script:
  # Install Nette Tester
  - composer install --no-interaction --dev --prefer-source
script: VERBOSE=true ./tests/run-tests.sh -s tests/
